### ISSUE TITLE
It will support the Windows10?

### ISSUE THREAD

**Issue by scillidan** [michelcrypt4d4mus/pdfalyzer#1]
I have `Windows10`, `python 3.10.2`. It seem don't work on my here:

```cmd
_pdfalyzer λ ppython pdfalyzer.py 
Traceback (most recent call last):
  File "D:\ketarin\_pdfalyzer\pdfalyzer.py", line 10, in <module>
    from lib.pdf_walker import PdfWalker
  File "D:\ketarin\_pdfalyzer\lib\pdf_walker.py", line 19, in <module>
    from lib.font_info import FontInfo
  File "D:\ketarin\_pdfalyzer\lib\font_info.py", line 6, in <module>
    from PyPDF2._cmap import build_char_map, prepare_cm
ImportError: cannot import name 'prepare_cm' from 'PyPDF2._cmap' (C:\Users\scillidan\scoop\apps\python\current\lib\site-packages\PyPDF2\_cmap.py)
```

**Comment by michelcrypt4d4mus** [comment]
that's an error with [a `PyPDF2` import statement](https://github.com/michelcrypt4d4mus/pdfalyzer/blob/19178314bd760f2037df0125ccb725c5b8b8d138/lib/font_info.py#L6), not an exception in the code of `pdfalyzer`.  seems like it should be fixable if `PyPDF2` works on windows 10.

**Comment by michelcrypt4d4mus** [comment]
to clarify - i don't have a windows 10 environment to test this on, but from the error message i would check your `PyPDF2` version. the `prepare_cm()` method was added on July 24th by [this PR](https://github.com/py-pdf/PyPDF2/pull/1162) so if you have an old version that would explain the error message.

**Comment by scillidan** [comment]
Thanks for your reminder. I remember that I forget to check the dependencies.
Finally, I install the package of `requirements.txt`. It works now :)

**Comment by scillidan** [comment]
It works on Windows. I just found it's `pdfalyze.exe` file to run it 🤡.
