### ISSUE TITLE
PdfWalkError - ref has no parent and is not indeterminate

### ISSUE THREAD

**Issue by Trigve** [michelcrypt4d4mus/pdfalyzer#6]
I've tried to use pdfalyzer for finding the problems with the form fields comb. But the PdfWalkError exception is thrown:
```Traceback (most recent call last):
  File "c:\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Python310-32\Scripts\pdfalyze.exe\__main__.py", line 7, in <module>
  File "c:\Python310-32\lib\site-packages\pdfalyzer\__init__.py", line 38, in pdfalyze
    pdfalyzer = Pdfalyzer(args.file_to_scan_path)
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 57, in __init__
    self.walk_node(self.pdf_tree)
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 82, in walk_node
    self.walk_node(next_node)
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 82, in walk_node
    self.walk_node(next_node)
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 77, in walk_node
    nodes_to_walk_next = [self._add_relationship_to_pdf_tree(r) for r in node.references_to_other_nodes()]
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 77, in <listcomp>
    nodes_to_walk_next = [self._add_relationship_to_pdf_tree(r) for r in node.references_to_other_nodes()]
  File "c:\Python310-32\lib\site-packages\pdfalyzer\pdfalyzer.py", line 156, in _add_relationship_to_pdf_tree
    raise PdfWalkError(f"{relationship} - ref has no parent and is not indeterminate")
pdfalyzer.util.exceptions.PdfWalkError: <83:AcroForm(Dictionary)> ref_key: /Fields, addr: /Fields[84] => nodeID 71 - ref has no parent and is not indeterminate
```

Unfortunately I cannot attach the .pdf, so I'm attaching the debug output.

[out.zip](https://github.com/michelcrypt4d4mus/pdfalyzer/files/9832262/out.zip)

**Comment by michelcrypt4d4mus** [comment]
thanks for the bug report. can you confirm what version you are running?
```
pdfalyze --version
```

**Comment by Trigve** [comment]
Sorry for forgetting the version: pdfalyzer 1.13.2

**Comment by michelcrypt4d4mus** [comment]
that log is... surprising. weirdly doesn't have almost any of the actual logs.  Can you maybe try again and run like this?
```
YARALYZER_LOG_LEVEL=DEBUG YARALYZER_LOG_DIR=/some/directory/ pdfalyze thedocument.pdf
```
(yes, that says `YARALYZER`)

also if you want to get around that error temporarily (which I am definitely considering degrading to a warning as i have with some other errors) you could change [this line](https://github.com/michelcrypt4d4mus/pdfalyzer/blob/master/pdfalyzer/pdfalyzer.py#L156) to a `pass` or similar... you won't get a complete tree but you'll probably get most of it.

**Comment by Trigve** [comment]
Thanks for the reply. I'm sending the yara log.

[yara.zip](https://github.com/michelcrypt4d4mus/pdfalyzer/files/9851613/yara.zip)

**Comment by michelcrypt4d4mus** [comment]
closing this for being old and not having an attached PDF (even though the problem may still exist).
